from pathlib import Path

"""
Replace this with your local SLformer project root.
"""
BASE_SLFORMER_DIR = Path("/home/jienihu/sc/SLformer")
BASE_DATA_DIR = BASE_SLFORMER_DIR / "data"
BASE_EXPERIMENT_DIR = BASE_SLFORMER_DIR / "experiment"
BASE_SAVED_DATA_DIR = BASE_DATA_DIR / "saved_data"
BASE_MAP_DIR = BASE_SAVED_DATA_DIR / "map"
BASE_EMB_DIR = BASE_SAVED_DATA_DIR / "emb"
BASE_GO_DIR = BASE_DATA_DIR / "GO"

""" 
Root path previously hardcoded as /home/guoyu/SLformer_interpretation in notebooks.
Replace with your local interpretation workspace root if different.
NOTE: Due to the ongoing process of explanation_groundtruth orgnizing, they will not be provided in the data source, if
you need to rerun the related notebooks, please contact the authors
"""
BASE_INTERPRETATION_DIR = Path("/home/guoyu/SLformer_interpretation")
BASE_INTERPRETATION_DATA_DIR = BASE_INTERPRETATION_DIR / "data"
BASE_INTERPRETATION_ALL_SL_DIR = BASE_INTERPRETATION_DATA_DIR / "all_SL"
BASE_INTERPRETATION_EXPL_GT_DIR = BASE_INTERPRETATION_DATA_DIR / "explanation_groundtruth"
BASE_INTERPRETATION_SAVED_DATA_DIR = BASE_SAVED_DATA_DIR / "saved_data"

"""
NOTE: If you intend to rerun the LLM section notebooks, please download those three model checkpoints first in huggingface
MedCPT: ncbi/MedCPT-Query-Encoder
mpnet: sentence-transformers/all-mpnet-base-v2
bge: BAAI/bge-large-en-v1.5

"""
BASE_MEDICAL_LLM_DIR = Path("/data/guoyu/HF-models")
# Centralized notebook data and experiment paths.
# For each entry, use your local equivalent generated by SLformer preprocessing
# or downloaded from your lab/project data mirror.
PATHS = {
    # Gene symbol -> integer ID mapping (generated map file).
    "gene2id_map": str(BASE_MAP_DIR / "gene2id.pkl"),

    # Ordered list of cancer types used in experiments (text file).
    "cancer_list": str(BASE_MAP_DIR / "cancer_list.txt"),

    # Co-expression sentence map without transformation for n=200.
    "gene2sent_n200_notransform_map": str(
        BASE_MAP_DIR / "gene2sent_n200_notransform.pkl"
    ),

    # Geneformer embedding map pickle.
    "geneformer_emb_map": str(BASE_MAP_DIR / "geneformer_emb.pkl"),

    # Geneformer embedding matrix (.npy).
    "geneformer_emb_mtx": str(BASE_EMB_DIR / "geneformer_emb.npy"),

    # Template for gene sentence map by sentence length n.
    "gene2sent_map_template": str(BASE_MAP_DIR / "gene2sent_n{sent_n}.pkl"),

    # Template for sentence mask map by sentence length n.
    "sent_mask_map_template": str(BASE_MAP_DIR / "sent_mask_n{sent_n}.pkl"),

    # GO ontology file (go-basic.obo from Gene Ontology release used in this project).
    "go_basic_obo": str(BASE_GO_DIR / "go-basic.obo"),

    # GOA human annotation file (.gaf).
    "goa_human_gaf": str(BASE_GO_DIR / "goa_human.gaf"),

    # UniProt-to-gene symbol ID mapping used by notebook GO mapping logic.
    "idmapping_tsv": str(BASE_GO_DIR / "idmapping_2024_11_09.tsv"),

    # Preprocessed GO annotation table used by XGB/prompt notebooks.
    "go_anno_popular_csv": str(BASE_GO_DIR / "go_anno_popular.csv"),

    # Inference directory for all-SL prediction outputs.
    "all_sl_inference_dir": str(BASE_EXPERIMENT_DIR / "inference" / "all_SL"),

    # Inference directory for IDH1-PRKDC single-pair experiments.
    "idh1_prkdc_inference_dir": str(BASE_EXPERIMENT_DIR / "inference" / "IDH1_PRKDC_single"),

    # Inference directory for PRMT5-MAT2A experiments.
    "prmt5_mat2a_inference_dir": str(BASE_EXPERIMENT_DIR / "inference" / "PRMT5_MAT2A_test"),

    # Saved embedding directory for IDH1-PRKDC run artifacts.
    "idh1_prkdc_emb_dir": str(BASE_EXPERIMENT_DIR / "emb" / "IDH1_PRKDC_emb"),

    # Ground-truth explanation table (manually curated CSV used in search_groundt notebook).
    "explanation_groundtruth_sheet1_csv": str(
        BASE_INTERPRETATION_EXPL_GT_DIR / "df_cite_all - Sheet1.csv"
    ),

    # Additional explanation table with PubMed query outputs.
    "explanation_groundtruth_pubmed_csv": str(
        BASE_INTERPRETATION_EXPL_GT_DIR / "df_cite_all - pubmed_id_query.csv"
    ),

    # Base directory for all-SL prediction CSVs/embedding files in interpretation workspace.
    "interpretation_all_sl_dir": str(BASE_INTERPRETATION_ALL_SL_DIR),

    # Co-expression similarity table generated for interpretation analyses.
    "cos_sim_kg_csv": str(BASE_INTERPRETATION_ALL_SL_DIR / "cos_sim_kg_sorted.csv"),

    # Functional cosine similarity table generated for interpretation analyses.
    "func_cos_sim_kg_csv": str(BASE_INTERPRETATION_ALL_SL_DIR / "func_cos_sim_kg.csv"),

    # Training fold template for mix+GBM dataset used in XGB analysis notebook.
    "mix_add_gbm_train_fold_template": str(
        BASE_INTERPRETATION_SAVED_DATA_DIR
        / "SL_train_test_data"
        / "mix_add_GBM_stratified"
        / "train_all_fold_{fold}.npy"
    ),

    # all-SL directory used by interpretation notebooks.
    "local_all_sl_dir": str(BASE_INTERPRETATION_ALL_SL_DIR),

    # Benchmark test fold template used by search_groundt notebook.
    "benchmark_mix_all_test_fold_template": str(
        BASE_INTERPRETATION_SAVED_DATA_DIR
        / "benchmark_data"
        / "mix_all"
        / "test_all_fold_{fold}.csv"
    ), 

    # Output directory for explanation-groundtruth artifacts.
    "local_explanation_groundtruth_dir": str(BASE_INTERPRETATION_EXPL_GT_DIR),

    "medcpt_model_dir": str(BASE_MEDICAL_LLM_DIR / "MedCPT-Query-Encoder"),
    "all-mpnet-base-v2": str(BASE_MEDICAL_LLM_DIR / "all-mpnet-base-v2"),
    "bge-large-en-v1.5": str(BASE_MEDICAL_LLM_DIR / "bge-large-en-v1.5")
}
