# /home/jienihu/sc/SLformer
EXPERIMENT_DIR: ./experiment
SAVED_DATA_DIR: /home/jienihu/sc/SLformer/data/saved_data
sc_dir: /data/xinliu/GeneSentence/TISCH2/

SL_data_dir: /home/jienihu/sc/SLformer/data/SL_data

# model_type = "geneformer" or "transformer"
model_type: transformer

# task = cancer_specific, mix, or cross_cancer
task:
  type: cancer_specific
  cancer: [KIRC, COAD, LAML, OV, BRCA, CESC, SKCM, LUAD]
  # cancer: [BRCA, CESC, LAML,COAD,LUAD]
  # mix_checkpoint:
  #   # path: ./experiment/mix/transformer/2024-07-04-20:25:34
  #   # path: ./experiment/mix/transformer/2024-07-04-20:26:56
  #   path: ./experiment/mix/transformer/2024-07-04-20:27:31

  # pretrain_checkpoint:
  #   path: /home/jienihu/sc/SLformer/experiment/pretrain/2024-07-24-20:07:54

SL_dataset:
  general:
    path: /home/jienihu/sc/SLformer/data/SL_data/raw/SLlabel_general.xlsx

