
EXPERIMENT_DIR: ./experiment
SAVED_DATA_DIR: /home/jienihu/sc/SLformer/data/saved_data
sc_dir: /data/xinliu/GeneSentence/TISCH2/

SL_data_dir: /home/jienihu/sc/SLformer/data/SL_data

# model_type = "geneformer" or "transformer"
model_type: transformer

# task = cancer_specific, mix, or cross_cancer
task: 
  type: cross_cancer
  # type: cross_cancer_all
  cancer: [KIRC, COAD, LAML, OV, BRCA, CESC, SKCM, LUAD]

SL_dataset:
  general:
    path: /home/jienihu/sc/SLformer/data/SL_data/raw/SLlabel_general.xlsx

