
EXPERIMENT_DIR: ./experiment
SAVED_DATA_DIR: ./data/saved_data

sc_dir: /data/xinliu/GeneSentence/TISCH2/
geneformer_gene_info_path: ../GeneFormer/gene_info_table.csv
geneformer_emb_dir: /data/xinliu/GeneSentence/TISCH2/geneformer_emb

SL_data_dir: ./data/SL_data

sc_samples:
  KIRC: KIRC_GSE159115
  COAD: CRC_EMTAB8107
  LAML: AML_GSE116256
  OV: OV_EMTAB8107
  BRCA: BRCA_GSE148673
  CESC: CESC_GSE168652
  SKCM: SKCM_GSE72056
  LUAD: NSCLC_GSE127465

add_sc_samples:
  Glioma: Glioma_GSE138794


SL_dataset:
  general:
    path: ./data/SL_data/raw/SLlabel_general.xlsx

