
EXPERIMENT_DIR: ./experiment
SAVED_DATA_DIR: ./data/saved_data

sc_dir: /data/xinliu/GeneSentence/TISCH2/
Geneformer_dir: ../GeneFormer
geneformer_gene_info_path: ../GeneFormer/gene_info_table.csv

SL_data_dir: ./data/SL_data

sc_samples:
  KIRC: KIRC_GSE159115
  COAD: CRC_EMTAB8107
  LAML: AML_GSE116256
  OV: OV_EMTAB8107
  BRCA: BRCA_GSE148673
  CESC: CESC_GSE168652
  SKCM: SKCM_GSE72056
  LUAD: NSCLC_GSE127465

add_sc_samples:
  Glioma: Glioma_GSE138794


SL_dataset:
  general:
    path: ./data/SL_data/raw/SLlabel_general.xlsx
  DBKO_study2:
    path: ./data/SL_data/processed/SLlabel_DBKO_study2.csv
    context: LAML
    label_type: rank
  primpartner_study2_binary:
    path: ./data/SL_data/processed/SLlabel_primpartner_study2_binary.csv
    context: LUAD
    label_type: binary
  primpartner_study2_viability: 
    path: ./data/SL_data/processed/SLlabel_primpartner_study2_viability.csv
    context: LUAD
    label_type: rank
  primpartner_study3_COAD: 
    path: ./data/SL_data/processed/SLlabel_primpartner_study3_COAD.csv
    context: COAD
    label_type: rank
  primpartner_study3_OV: 
    path: ./data/SL_data/processed/SLlabel_primpartner_study3_OV.csv
    context: mix
    label_type: rank
  paralog_study1_score:
    path: ./data/SL_data/processed/SLlabel_paralog_study1_score.csv
    context: mix
    label_type: rank
  paralog_study2_score: 
    path: ./data/SL_data/processed/SLlabel_paralog_study2_score.csv
    context: mix
    label_type: rank
  paralog_study3: 
    path: ./data/SL_data/processed/SLlabel_paralog_study3_binary.csv
    context: SKCM
    label_type: binary
