
EXPERIMENT_DIR: ./experiment
SAVED_DATA_DIR: ./data/saved_data
sc_dir: /data/xinliu/GeneSentence/TISCH2/

SL_data_dir: ./data/SL_data

# model_type = "geneformer" or "transformer"
model_type: transformer

task: 
  type: fewshot
  # cancer_out: OV
  cancer_out: BRCA
  # mix_checkpoint: ./experiment/fewshot/2024-10-29-00:25:29
  mix_checkpoint: ./experiment/fewshot/2024-11-08-22:43:57
  # cross-cancer_checkpoint

SL_dataset:
  general:
    path: ./data/SL_data/raw/SLlabel_general.xlsx

