EXPERIMENT_DIR: ./experiment
SAVED_DATA_DIR: ./data/saved_data
sc_dir: /data/xinliu/GeneSentence/TISCH2/
SL_data_dir: ./data/SL_data
task:
  type: att
  # 'KIRC', 'COAD', 'LAML', 'OV', 'BRCA', 'CESC', 'SKCM', 'LUAD'
  # name: IDH1_PRKDC_att_50
  # primary_gene: IDH1
  # partner_gene: PRKDC
  # cancer: Glioma
  name: BRCA_PARP_att_50_LUAD
  primary_gene: BRCA2
  partner_gene: PARP1
  cancer: SKCM
  model:
    model_no_0: experiment/mix_add_GBM/transformer/50len/2025-06-14-20:51:01
    model_no_1: experiment/mix_add_GBM/transformer/50len/2025-06-15-06:25:58
    model_no_2: experiment/mix_add_GBM/transformer/50len/2025-06-14-22:15:40
    model_no_3: experiment/mix_add_GBM/transformer/50len/2025-06-15-01:38:21
    model_no_4: experiment/mix_add_GBM/transformer/50len/2025-06-15-07:46:12
    model_no_5: experiment/mix_add_GBM/transformer/50len/2025-06-14-19:39:30
    model_no_6: experiment/mix_add_GBM/transformer/50len/2025-06-15-02:53:47
    model_no_7: experiment/mix_add_GBM/transformer/50len/2025-06-14-18:26:16
    model_no_8: experiment/mix_add_GBM/transformer/50len/2025-06-14-23:36:08
    model_no_9: experiment/mix_add_GBM/transformer/50len/2025-06-15-05:17:58
    model_no_10: experiment/mix_add_GBM/transformer/50len/2025-06-14-17:09:51
    model_no_11: experiment/mix_add_GBM/transformer/50len/2025-06-14-09:34:30
    model_no_12: experiment/mix_add_GBM/transformer/50len/2025-06-15-00:30:53
    model_no_13: experiment/mix_add_GBM/transformer/50len/2025-06-14-13:57:51
    model_no_14: experiment/mix_add_GBM/transformer/50len/2025-06-14-06:15:21
    model_no_15: experiment/mix_add_GBM/transformer/50len/2025-06-14-11:38:56
    model_no_16: experiment/mix_add_GBM/transformer/50len/2025-06-14-16:09:19
    model_no_17: experiment/mix_add_GBM/transformer/50len/2025-06-14-08:32:51
    model_no_18: experiment/mix_add_GBM/transformer/50len/2025-06-14-15:07:43
    model_no_19: experiment/mix_add_GBM/transformer/50len/2025-06-15-04:12:17
    model_no_20: experiment/mix_add_GBM/transformer/50len/2025-06-14-05:02:39
    model_no_21: experiment/mix_add_GBM/transformer/50len/2025-06-14-07:19:01
    model_no_22: experiment/mix_add_GBM/transformer/50len/2025-06-14-12:49:18
    model_no_23: experiment/mix_add_GBM/transformer/50len/2025-06-14-10:36:33
