EXPERIMENT_DIR: ./experiment
SAVED_DATA_DIR: ./data/saved_data
sc_dir: /data/xinliu/GeneSentence/TISCH2/
SL_data_dir: ./data/SL_data
task:
  type: IDH1_permute_inference
  gene_list: ./data/DDR_genelist/reactome_dna_repair.txt
model:
  model_no_12: ./experiment/mix_add_GBM/transformer/2024-11-28-11:30:19
  model_no_14: ./experiment/mix_add_GBM/transformer/2024-11-27-23:21:16
  model_no_15: ./experiment/mix_add_GBM/transformer/2024-11-28-10:32:45
  model_no_30: ./experiment/mix_add_GBM/transformer/2024-11-28-06:45:00
  model_no_39: ./experiment/mix_add_GBM/transformer/2024-11-27-02:56:25