
EXPERIMENT_DIR: ./experiment
SAVED_DATA_DIR: ./data/saved_data
sc_dir: /data/xinliu/GeneSentence/TISCH2/

SL_data_dir: ./data/SL_data

task: 
  type: inference
  name: IDH1_DDR_Glioma_test
  # name: IDH1_DDR_LAML_test
  data:
    kegg: ./data/saved_data/inference/IDH1_DDR_Glioma_kegg.npy
    reactome: ./data/saved_data/inference/IDH1_DDR_Glioma_reactome.npy
    # kegg: ./data/saved_data/inference/IDH1_DDR_LAML_kegg.npy
    # reactome: ./data/saved_data/inference/IDH1_DDR_LAML_reactome.npy
  model:
    cross_cancer_no1: 
      model_type: transformer
      path: ./experiment/cross_cancer/transformer/2024-08-30-15:46:22
    cross_cancer_no2: 
      model_type: transformer
      path: ./experiment/cross_cancer/transformer/2024-08-30-10:24:21
    cross_cancer_no2.6: 
      model_type: transformer
      path: ./experiment/cross_cancer/transformer/2024-08-31-15:45:43
    cross_cancer_no2.7: 
      model_type: transformer
      path: ./experiment/cross_cancer/transformer/2024-08-31-10:38:23
    cross_cancer_no2.8: 
      model_type: transformer
      path: ./experiment/cross_cancer/transformer/2024-08-31-12:52:00
    cross_cancer_no2.9: 
      model_type: transformer
      path: ./experiment/cross_cancer/transformer/2024-08-31-03:54:44
    cross_cancer_no3: 
      model_type: transformer
      path: ./experiment/cross_cancer/transformer/2024-08-30-17:08:59
    cross_cancer_no3.1: 
      model_type: transformer
      path: ./experiment/cross_cancer/transformer/2024-08-31-11:49:08
    cross_cancer_no3.2: 
      model_type: transformer
      path: ./experiment/cross_cancer/transformer/2024-08-31-17:19:46
    cross_cancer_no3.3: 
      model_type: transformer
      path: ./experiment/cross_cancer/transformer/2024-08-31-13:44:54
    cross_cancer_no3.4: 
      model_type: transformer
      path: ./experiment/cross_cancer/transformer/2024-08-31-09:31:29
    cross_cancer_no4: 
      model_type: transformer
      path: ./experiment/cross_cancer/transformer/2024-08-30-14:00:11
    cross_cancer_no5: 
      model_type: transformer
      path: ./experiment/cross_cancer/transformer/2024-08-30-19:41:33
    cross_cancer_no6: 
      model_type: transformer
      path: ./experiment/cross_cancer/transformer/2024-08-30-21:17:15
    cross_cancer_no7: 
      model_type: transformer
      path: ./experiment/cross_cancer/transformer/2024-08-31-00:05:36
    cross_cancer_no8: 
      model_type: transformer
      path: ./experiment/cross_cancer/transformer/2024-08-30-11:20:24
    
    

SL_dataset:
  general:
    path: ./data/SL_data/raw/SLlabel_general.xlsx

