# Directory settings (adjust paths as necessary)
EXPERIMENT_DIR: ./experiment
SAVED_DATA_DIR: /home/jienihu/sc/SLformer/data/saved_data
sc_dir: /data/xinliu/GeneSentence/TISCH2/
SL_data_dir: /home/jienihu/sc/SLformer/data/SL_data

# Model type
model_type: transformer

# Task-specific settings
task:
  type: cancer_specific
  cancer: [SKCM]

# Dataset-specific settings
SL_dataset:
  general:
    path: /home/jienihu/sc/SLformer/data/SL_data/raw/SLlabel_general.xlsx

# Model parameters specific to BRCA
params:
  wandb_track: 0
  save_model: 0
  add_att: 1
  att_nhead: 2
  batch_size: 512
  transformer_hidden_dim: 256
  dropout: 0.1
  eps: 1e-5
  weight_decay: 1e-5
  n_head: 1
  num_layers: 1
  n: 10
  early_stop: 25
  save_result: 1
  lr_patience: 8
  transformer_lr: 1e-4
  predictor_lr: 1e-3
  device: 1
  d_model: 512
  mlp_hidden_dim: 256
