EXPERIMENT_DIR: ./experiment
SAVED_DATA_DIR: ./data/saved_data
sc_dir: /data/xinliu/GeneSentence/TISCH2/
SL_data_dir: ./data/SL_data

task:
  type: SL_inference
  name: IDH1_PRKDC
  data:
    all: ./data/saved_data/inference/IDH1_PRKDC_allcancer.npy
  model:
    model_name0: path_to_model
    model_name1: path_to_model
    # ...
    
SL_dataset:
  general:
    path: ./data/SL_data/raw/SLlabel_general.xlsx
