EXPERIMENT_DIR: ./experiment
SAVED_DATA_DIR: ./data/saved_data
sc_dir: /data/xinliu/GeneSentence/TISCH2/

SL_data_dir: ./data/SL_data

task: 
  # type: independent_test
  type: independent_test_on_mix
  model:
    mix:
      model_type: transformer
      path: path_to_model
    CESC:
      model_type: transformer
      path: path_to_model
    OV:
      model_type: transformer
      path: path_to_model
    LAML:
      model_type: transformer
      path: path_to_model
    LUAD:
      model_type: transformer
      path: path_to_model
    COAD:
      model_type: transformer
      path: path_to_model
    SKCM:
      model_type: transformer
      path: path_to_model

SL_dataset:
  general:
    path: ./data/SL_data/raw/SLlabel_general.xlsx
  DBKO_study2:
    path: ./data/SL_data/processed/SLlabel_DBKO_study2.csv
    context: LAML
    label_type: rank
  primpartner_study2_binary:
    path: ./data/SL_data/processed/SLlabel_primpartner_study2_binary.csv
    context: LUAD
    label_type: binary
  primpartner_study2_viability: 
    path: ./data/SL_data/processed/SLlabel_primpartner_study2_viability.csv
    context: LUAD
    label_type: rank
  primpartner_study3_COAD: 
    path: ./data/SL_data/processed/SLlabel_primpartner_study3_COAD.csv
    context: COAD
    label_type: rank
  primpartner_study3_OV: 
    path: ./data/SL_data/processed/SLlabel_primpartner_study3_OV.csv
    context: OV
    label_type: rank
  paralog_study1_score:
    path: ./data/SL_data/processed/SLlabel_paralog_study1_score.csv
    context: mix
    context_all: 
      - CESC
      - LUAD
    label_type: rank
  paralog_study2_score: 
    path: ./data/SL_data/processed/SLlabel_paralog_study2_score.csv
    context: mix
    context_all: 
      - COAD
      - LUAD
      - OV
    label_type: rank
  paralog_study3: 
    path: ./data/SL_data/processed/SLlabel_paralog_study3_binary.csv
    context: SKCM
    label_type: binary
